# async-only: true
extension: ['ts']
jobs: 1
package: './package.json'
parallel: false
recursive: false
reporter: 'spec'
retries: 1
slow: '500'
spec:
  - 'tests/**/*.spec.ts'
timeout: '10000'
ui: 'bdd'
